version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/wineflix
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60
  ApplicationStart:
    - location: scripts/npm-react-dev.sh
      runas: root
      timeout: 60